class ValidationError(ValueError): ...
class ResourceLimitError(RuntimeError): ...

class DecodeResult:
    @property
    def codeword(self) -> int: ...
    @property
    def selected_terms(self) -> list[int]: ...
    @property
    def distance(self) -> int: ...
    @property
    def candidates(self) -> int: ...
    @property
    def ties(self) -> int: ...

def rm_dimension(qubits: int, order: int) -> int: ...
def rm_basis_terms(qubits: int, order: int) -> list[int]: ...
def rm_generator_rows(qubits: int, order: int) -> list[int]: ...
def decode_exact(received: int, qubits: int, order: int) -> DecodeResult: ...
def synthesize_linear_map(rows: list[int]) -> list[tuple[int, int]]: ...
